### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by NetanelBasal** [RyanHouben98/medium-clone#1]
You can call store.reset() :)

https://github.com/RyanHouben98/medium-clone/blob/master/src/app/core/repositories/auth.repository.ts#L23

**Comment by RyanHouben98** [comment]
> You can call store.reset() :)
> 
> https://github.com/RyanHouben98/medium-clone/blob/master/src/app/core/repositories/auth.repository.ts#L23
Thanks for the tip! This is my first project with elf, really like it!
